name: Build Lambda All Platforms

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    name: Build macOS
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Mac CLI single-file
        run: pyinstaller --noconfirm --onefile Lambda.py

      - name: Build Mac GUI App bundle
        run: pyinstaller --noconfirm --onedir --windowed Lambda.py

      - name: Upload Mac-CLI binary
        uses: actions/upload-artifact@v7
        with:
          path: dist/Lambda
          archive: false
          name: mac-cli-binary

      - name: Upload Mac-GUI Lambda.app
        uses: actions/upload-artifact@v7
        with:
          path: dist/Lambda.app
          name: mac-gui-app


  build-windows:
    name: Build Windows
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Windows single-file exe
        run: pyinstaller --noconfirm --onefile Lambda.py

      - name: Upload Windows exe
        uses: actions/upload-artifact@v7
        with:
          path: dist/lambda.exe
          archive: false
          name: windows-exe


  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Linux single-file binary
        run: pyinstaller --noconfirm --onefile Lambda.py

      - name: Upload Linux binary
        uses: actions/upload-artifact@v7
        with:
          path: dist/Lambda
          archive: false
          name: linux-binary
